version: '3'  #pick number version
services:   #which service to run declare from here
  backend:  #name of serivce, pick by your own
    build: .  #mean base on Dockerfile
    ports:  
      - 8000:8000   #local:container
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=fastapi-advance
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: 12-alpine
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fastapi-advance
     #- POSTGRES_USER=<if you use default 'postgres' username, please ignore this!
