version: "3"
services:
  backend:
    image: rickychan1987/fastapi-advance
    depends_on:
      - postgres
    ports:
      - 80:8000 #local:container
    #w/ production we dont need to adjust code again
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres:12.10-alpine
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      #- POSTGRES_USER=<if you use default 'postgres' username, please ignore this!

    #create an volumes to store data when container down
    volumes:
      - postgres-db:/var/lib/postgres/data #<name volume>:<default stored data in container>

volumes: #volumes at globally
  postgres-db: #this for multiple container able to access this.
