version: "3" #pick number version
services: #which service to run declare from here
  backend: #name of serivce, pick by your own
    build: . #mean base on Dockerfile
    depends_on: #backend service wait postgres start first
      - postgres
    ports:
      - 8000:8000 #local:container
    volumes:
      - ./:/usr/src/app:ro #./ which mean current dir, u can specify locate such ./app, :ro => (read-only)
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres #given this hostname as same postgres container
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=fastapi-advance
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres:12.10-alpine #this choose version 12.10 alpine tag
    environment:
      - POSTGRES_PASSWORD=1234 #match w/databse password
      - POSTGRES_DB=fastapi-advance #match w databse name .env file
      #- POSTGRES_USER=<if you use default 'postgres' username, please ignore this!

    #create an volumes to store data when container down
    volumes:
      - postgres-db:/var/lib/postgres/data #<name volume>:<default stored data in container>

volumes: #volumes at globally
  postgres-db: #this for multiple container able to access this.
