"""add phone number to user table

Revision ID: 908d24aee4b2
Revises: a706a61f2a42
Create Date: 2022-03-31 02:14:29.796506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908d24aee4b2'
down_revision = 'a706a61f2a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
